// Place to import fontawesome icons
import { library } from "@fortawesome/fontawesome-svg-core";

import {
    faBars,
    faUser,
    faBell,
    faEye,
    faEyeSlash,
    faGear,
    faRightFromBracket,
    faSun,
    faMoon,
    faMagnifyingGlass,
    faFilter,
    faSort,
    faSortDown,
    faSortUp,
    faEllipsisV,
    faAngleDown,
    faTimesCircle,
    faEdit,
    faExclamationTriangle,
    faCircleCheck,
    faCircleInfo,
    faCircleExclamation,
    faCircleXmark,
    faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faBars,
    faUser,
    faBell,
    faEye,
    faEyeSlash,
    faGear,
    faRightFromBracket,
    faSun,
    faMoon,
    faMagnifyingGlass,
    faFilter,
    faSort,
    faSortDown,
    faSortUp,
    faEllipsisV,
    faAngleDown,
    faTimesCircle,
    faEdit,
    faExclamationTriangle,
    faCircleCheck,
    faCircleInfo,
    faCircleExclamation,
    faCircleXmark,
    faXmark,
);